//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class pro13Entities : DbContext
    {
        private static pro13Entities _context;
        public pro13Entities()
            : base("name=pro13Entities")
        {
        }
        public static pro13Entities GetContext()
        {
            if (_context == null)
                _context = new pro13Entities();
            return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PRAuto> PRAuto { get; set; }
        public virtual DbSet<PRClient> PRClient { get; set; }
        public virtual DbSet<PRProkat> PRProkat { get; set; }
    }
}
